### ISSUE TITLE
set tomato's xiangqi pieces as default xiangqi pieces

### ISSUE THREAD

**Issue by NelloHo** [gbtami/pychess-variants#1009]
tomato has made the new xiangqi pieces set , I suggest we set it as default:
![image](https://user-images.githubusercontent.com/99171663/193265573-40feb46c-d9b4-4985-9fc2-32374714373f.png)
this is the current one:
![image](https://user-images.githubusercontent.com/99171663/193265711-ecfbb428-2bfe-4372-a721-7c9c3d6e01a9.png)

**Comment by gbtami** [comment]
@CouchTomato87 ?

**Comment by CouchTomato87** [comment]
I don't think that board is the current default, but anyways, I don't have any issue. Although my only concern is that because it's essentially a copy of the TTXQ board, it might seem a little too much of a copy. I actually made the current defaults so that ours would be separate from the PlayOK ones lol.

**Comment by gbtami** [comment]
Yea, the gray paper board is the default. I think we can leave the defaults as is. Everyone can customize it, and it is a matter of taste anyway.
