### ISSUE TITLE
Duck Chess

### ISSUE THREAD

**Issue by ddugovic** [gbtami/pychess-variants#1014]
Chess.com recently added this variant: https://duckchess.com/

**Comment by gbtami** [comment]
You should open this issue in https://github.com/ianfab/Fairy-Stockfish/issues first to let pychess consider it :)
Feel free to re open this when Fairy supports it.

**Comment by PeterNjeim** [comment]
Fairy-StockFish now supports the Duck Chess variant in the `duck` branch. This should be re-opened

**Comment by gbtami** [comment]
Pychess uses Fairy-Stockfish master branch only (via pyffish and ffish.js), but as ubdip said "Previously I would have said no way, but now it at least has a non-zero probability."

**Comment by gbtami** [comment]
Anyone can test it on our DEV site at https://pychess-variants-dev.onrender.com
Analysis page is not adjusted to make duck moves rn.

**Comment by gbtami** [comment]
Deployed.

**Comment by PeterNjeim** [comment]
Thanks, it's working very well.

Bugs:
- Can't enable Fairy-Stockfish toggle in Analysis Board for Duck variant
- Can't undo a pre-Duck move when playing (probably due to https://github.com/gbtami/pychess-variants/issues/523)
- Possible Duck moves aren't visible for the very first move

Feature requests:
- Ability to move Duck without clicking on it (similar to how the very first move of the game works)
- Duck Chess with checks variant (https://github.com/ianfab/Fairy-Stockfish/issues/556) (Note that Fairy-Stockfish doesn't support it, so I know PyChess won't either)

**Comment by gbtami** [comment]
Yes, because https://github.com/fairy-stockfish/fairy-stockfish.wasm has no duck chess support at all.

Undo is not implemented atm, see https://github.com/gbtami/pychess-variants/issues/355, but you can reload the page before duck moved.

In general possible move targets are visible after you select a piece to move. But the duck is not on the board when the game starts and the very first duck move is one click only, so this feature can't be triggered.

Ability to move Duck without clicking on it is not possible as well. There is no duck there to move :)
Adding it to white pocket is also problematic, because Duck chess is not a drop variant in Fairy-Stockfish.

**Comment by PeterNjeim** [comment]
Thanks for the information. So the engine is still the random engine when playing against AI? I thought it wasn't because it said it is Fairy-Stockfish when the random moves toggle is off. It seems to play quite strongly, so I'm not sure

**Comment by gbtami** [comment]
If you play against AI (when the random moves toggle is off) you play against Fairy-Stockfish running on a fairifishnet distributed network worker. What is not working atm is the in browser analysis, because it is based on https://github.com/fairy-stockfish/fairy-stockfish.wasm
Playing and server side analysis is based on https://github.com/ianfab/Fairy-Stockfish/tree/duck
