### ISSUE TITLE
Fairy Stockfish timeout

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#109]
https://pychess-variants.herokuapp.com/Xj9gfrWo

Apparently it took like 5 minutes to make its move

**Comment by gbtami** [comment]
Unfortunately this may happen any time, because we have very few fairyfishnet workers (only 4).
If they are busy with analysis/play or can't respond for any reason (network problems etc.) A.I. will not respond. Other bugs can happen of course, but in this particular game Fairy can continue a new game from the final position without any issue.
