### ISSUE TITLE
Mansindam repetition result

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#1205]
https://www.pychess.org/w8oJhTM0?ply=57
Shouldnt the result be the opposite?
@ianfab what do you think?

**Comment by ianfab** [comment]
Non draw repetitions are notoriously difficult to understand, but this looks fine to me. It is black to move, and nFoldValue is loss, so black loses.

**Comment by gbtami** [comment]
Wait, therules say: 
"About Prohibition of Threefold Repetition
Neither White nor Black can repeat the same situation three times. Even if it is not repeated in succession, if the same situation is repeated twice in one game, no one can repeat the situation again."
Here the BOT repeated the position 3rd time with its latest move. Is this correct? If yes, then possible the .ini definition is not what the game creator wanted to achieve?

**Comment by ianfab** [comment]
The description is somewhat ambiguous, but it might be a bug in the definition of the INI, yes. As described above the reasoning what the adjudication does here is pretty straightforward (even though detecting the first point of repetition might be tricky) and looks correct given the variant definition. Either way this kind of non-draw repetition adjudication hardly ever results in what a human would expect, since intermediate moves and the like can really mess up your intuition about who is repeating first.

**Comment by gbtami** [comment]
@Snowmoondaphne any thoughts?

**Comment by Snowmoondaphne** [comment]
As stated in the Rule, White and Black cannot repeat the same situation more than 3 times. No one can repeat that situation more than 3 times, no matter who started it, and no matter if it hasn't been repeated in a row

There is no different opinion if this rule is properly maintained. Actually, I'm not sure what to answer because I'm not familiar with programming

https://www.pychess.org/puzzle/EWCQv
Looking at this puzzle, it seems that Mansindam's repetition error has been fixed

**Comment by gbtami** [comment]
OK, I double checked the rules text of Mansindam. It say that stealmate is loss for the side who can't move and repetition is loss for the side repeating the position 3rd time. This is similar in Tori Shogi (except that nFoldRule = 4 there). So I checked the rules of Tori Shogi here https://github.com/fairy-stockfish/Fairy-Stockfish/blob/master/src/variant.cpp#L925C11-L925C11
```
        v->stalemateValue = -VALUE_MATE;
        v->nFoldValue = VALUE_MATE;
```
Contrary in .ini of mansindam:
```
stalemateValue = loss
nFoldValue = loss
```

I think nFoldValue should be "win". Am I correct?

Btw I find the same mistake in Empire chess definition. For example in this game https://www.pychess.org/7LZIGzbJ the result should be 0-1, not 1-0.
