### ISSUE TITLE
FR: Arimaa board game

### ISSUE THREAD

**Issue by phoe** [gbtami/pychess-variants#1312]
https://en.wikipedia.org/wiki/Arimaa

The game is interesting and played with chess-like hardware (8x8 board with 4 marked traps, pieces in 8-2-2-2-1-1 numbers), although the rules permit a player to make up to four moves per turn instead of just one. There exist computer engines.

What is the process of adding a new chess-like game such as this to pychess-variants?

**Comment by gbtami** [comment]
The first requirement to add a new game to pychess is Fairy-Stockfish have to support it, because we don't implement the game rules ourselves but use FSF knowledge via its python/js bindings.
Because of this Arimaa is not possible atm, see https://github.com/fairy-stockfish/Fairy-Stockfish/issues/343
If this changes in the future feel free to reopen this issue.
