### ISSUE TITLE
when i lost on time, pychess reported that i'd won on time at game conclusion

### ISSUE THREAD

**Issue by mattgatto** [gbtami/pychess-variants#1588]
**Exact URL where the bug happened**
https://www.pychess.org/U5zv0Xgy

**Steps to reproduce the bug**
no idea, and i haven't encountered this bug before

**What did you expect to happen?**
i lost on time and should have lost rating points

**What happened instead?**
pychess.org said i won on time and awarded me rating points for a win

**Operating system and browser version**
Google Chrome Version 127.0.6533.119 (Official Build) (64-bit)
Fedora Linux 40

![image](https://github.com/user-attachments/assets/c594ea96-a38c-4070-b5f1-7814a80edc42)

**Comment by gbtami** [comment]
It would be good to have more info from the other side as well if ZugAddict can remember anything. Was he reconnecting or reloading or anything special after he made 19...d4? Were the clocks on his monitor OK? I mean similar to this.
Something "extra" have to be here, because the basic clock timeout handling code seems OK for me.

**Comment by mattgatto** [comment]
maybe he timed out? i dunno

**Comment by gbtami** [comment]
Another one:
https://www.pychess.org/KwU4C6cI?ply=50
