### ISSUE TITLE
Minor enhancements for the Editor page

### ISSUE THREAD

**Issue by notruck** [gbtami/pychess-variants#190]
Looking at the Lichess editor, some of their features seem useful. They could probably improve some others. 
![lichess-editor](https://user-images.githubusercontent.com/56622488/77435520-a1ccc280-6d9f-11ea-8e0f-edcff9ff084c.png)

We probably don't need the castling rights checkboxes. If included, they may require different implementations for different variants. S-chess might also need gating checkboxes.  

- [x] Flip board option

- [x] Castlings option

- [x] Include graphic (font?) icons in front of the blue text options?

- [x] A [Copy FEN] button next to the FEN field to copy the string to the clipboard

Lichess deals with the "side to move" with a drop-down list. Either of the following might be a slight improvement perhaps. 

- [x] A "Black to move" checkbox to update the FEN from 'w' to 'b' 
 (or) 
- [x] A button that toggles between [White to move] and [Black to move] that does the same thing

Again, most of those are non-essential features. Thank you!

**Comment by gbtami** [comment]
Curious2021 suggested in https://github.com/gbtami/pychess-variants/issues/395
"As of right now the only way to input pieces using the Pychess editor is to drag and drop them onto the board. But point and click would be much faster since there would be less chance of mouse slips setting up the boards by a mouse. And it allows quicker board setup."
