### ISSUE TITLE
Change default Shogi notation

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#239]
I know there was talk about allowing different notations, but if that's not in the pipeline anytime soon, can we actually switch to Hosking notation (number number)? After being involved in Shogi communities for a while, really no one at all uses the Hodges notation (number letter). I also struggle with it because I can't count letters easily.

**Comment by gbtami** [comment]
Yes, of cousre!

**Comment by ianfab** [comment]
I am not so sure if the conclusion is sound. Hodges is maybe not that common, but in my experience Hosking is even less, since we have to distinguish between Hodges vs. Hosking and number vs. letter in general. I hardly ever see any usage of Hosking notation except for in Hosking's books, whereas Hodges is used by various authors. E.g., among the shogi books I have there roughly are equal amounts of books using Hodges, figurine notation (with numbers), Japanese notation, and Hosking. Since three of the four use numbers, notations with numbers are prevalent, but Hosking is not.

**Comment by gbtami** [comment]
If I understand correctly implementing notation chooser in settings dialog similar to pieces/boards seems better solution.

**Comment by CouchTomato87** [comment]
I guess I shouldn't be using Hodges and Hoskin but really, it's the number-number style. Yes, books use a lot of different styles, but among shogi players actually playing right now, it's pretty much unanimously numbers. I've heard a few people even express frustration with Pychess because it uses letters, actually.

To gbtami's point, choosing would certainly help. Although you'd have to be able to change the coordinates on the board as well.

**Comment by ianfab** [comment]
If people use a certain notation they do that because they read it somewhere. And if it is not about books, then it has to be a certain app or website, e.g., 81dojo?

In my experience and opinion
* number-number is closer to Japanese notation than number-letter, so it is preferable
* `*` is way more common than `'` for drops
* using `-` as a separator for quiet moves is very common

Therefore, my best proposal for a consensus notation would be using Hodges with number-number format, i.e., a hybrid of Hodges and Hosking. This would be also be very close to the figurine (Kitao–Kawasaki) notation that many Shogi players might be familiar with, as well as to what 81dojo calls "chess-order" notation (just that promoted pieces would be noted with `+` like in Hosking/Hodges, e.g., +P-11 instead of T-11). If this is desired I could add this as a third shogi notation in pyffish and make it the default.

The board coordinates would of course need to be adjusted accordingly. As I just noticed, the board coordinates for shogi are currently anyway buggy as the files and ranks are in reverse order.

**Comment by CouchTomato87** [comment]
I think a lot of current practice does derive from 81dojo. The most recent books are the "At a Glance" series which use Kitao-Kawasaki notation, although that's not really used in the west at all because you still have to type the kanji out. 

I mostly agree with your points:
-Number-number not only because of Japanese, but also because it's much easier to count (multiple shogi players have stated this) than letters.
-\* is indeed way more common than ' for drops.
-I have actually not seen - used as a separator, but any debate about using or not using that is trivial.

And yep, I do agree with the proposal. The only other point is that D and H are commonly used for dragon and horse, although it's really 50-50. D and H tend to be used by more established players, while +R and +B tend to be used to by new players for obvious reasons.

**Comment by gbtami** [comment]
@ianfab I'm fine with your proposal also.
@CouchTomato87 just notice that number-number may be easier for Shogi players, but for new players coming from western chess letter-number is definitely easier  :)

**Comment by ianfab** [comment]
Pyffish change is ready. The notation enum in chessgroundx should be updated accordingly along with the labels for the ranks.

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/f5b8387a5b4ed0e748c75c076fdc092cc4bc093b
