### ISSUE TITLE
Last move highlight issue

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#26]
https://pychess-variants.herokuapp.com/er8NiidB
![lastmove](https://user-images.githubusercontent.com/479964/64197241-d7eb3900-ce85-11e9-945a-536f5489fad1.png)

**Comment by CouchTomato87** [comment]
Speaking of last move highlights, if there was a drop, could we get a highlight from the corresponding spot in the pieces in hand? I often get confused if there was a drop or not because if there is a green piece in the middle of the board, I have to check all corners to make sure it just wasn't a long move.

**Comment by gbtami** [comment]
Agreed that it would be good. Filed it as #27
