### ISSUE TITLE
Can't drop to a1 in grandhouse

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#29]
ubdip @gbtami: somehow in our last game the a1 square was buggy. sometimes the white rook was invisible, and at one point I could not drop a black rook
https://pychess-variants.herokuapp.com/okWFGjuv
ubdip move 38

**Comment by ianfab** [comment]
Some more info now, since I had to leave in a hurry:
- The issue with the disappearing rook was that sometimes after one player moved, the white rook on a1 was gone, but after the other player moved it reappeared again (I unfortunately do not remember whether after white's or black's move, but I think the pattern was always the same).
- On the 38th move I repeatedly tried to drop the rook on a1 but it did not work, so I finally dropped it on b1 which worked fine.

**Comment by gbtami** [comment]
Can you remember these?
1. How you tried the drop move? Using DnD or click-click method?
2. Was all other empty squares marked as possible targets with little circles except 'a1'?

**Comment by ianfab** [comment]
1. Drag and drop.
2. I don't remember, but since someone in the chat mentioned it is reproducible, maybe he can answer it.

**Comment by gbtami** [comment]
Thx, will try to reproduce.

**Comment by gbtami** [comment]
OK, reproduced it. 'a0' is used in drop moves as 'from' sqare in chessground and I use 0-based ranks in xinagqi and in grand variants. It was not a problem until garndhouse appeared :)

![grandhouse](https://user-images.githubusercontent.com/479964/64344542-f3be1e80-cfee-11e9-84ae-f43bf2de4b87.png)

**Comment by CouchTomato87** [comment]
Keep that in mind when you inevitably come to xianghouse ;)
