### ISSUE TITLE
Bug on S-chess house

### ISSUE THREAD

**Issue by LittleSwordsman** [gbtami/pychess-variants#30]
Sometimes when the ai captures with the bishop it duplicates. For example bishop takes pawn but instead of going onto the square of the captured pawn a new bishop appears where the pawn got captured and the original bishop that made the capture remains on its original square and it doesn't count it as a dropping a previously captured bishop.
Dont know if this makes sense reply if confused.
Thanks.
Look at move 20:
https://pychess-variants.herokuapp.com/RFp9UeUr

**Comment by ianfab** [comment]
It might look confusing at first sight, but it is not a bug. On move 20, Black uses the bishop on c8 to capture on h3 and at the same time gates the bishop he has in hand on c8. So actually the bishop moved, but since a new one appears on c8, it looks as if it would not have moved. On move 21, the gated bishop from c8 just does a normal capturing move on h3, so that should also be fine.
