### ISSUE TITLE
Announcement/Changelog

### ISSUE THREAD

**Issue by Fulmene** [gbtami/pychess-variants#312]
Some users report wanting an announcement so that they know when new variants are added to the site. This could also be used for something like bug fixing and feature announcements as well.

**Comment by gbtami** [comment]
Maybe we should use https://prismic.io/ free open content plan to integrate/create/publish blog posts similar how lichess uses it in https://lichess.org/blog
See https://prismic.io/headless-cms-intro

**Comment by CouchTomato87** [comment]
All for this. It also allows contributors like Jarl to take a more active role.

**Comment by gbtami** [comment]
Instead of using prismic.io I went to the simpler way. We can write posts in static/news/*.md
This works similar to static/docs/*.md for Learn menu.
Only expectation is to add the standard header part to posts you can see in https://github.com/gbtami/pychess-variants/edit/master/static/news/First%20Blog%20Post.md now.
Maybe we can polish this if we want to.

Implementation of post list section hardwired in client/lobby.ts and server/news.py now, but I plan to make it "data driven" later.
