### ISSUE TITLE
Premove bug

### ISSUE THREAD

**Issue by kezsulap** [gbtami/pychess-variants#318]
https://www.pychess.org/9OEnwxfe
On move 23 I played Bxe6 and premoved Exe6. On my side the board looked normal till this point, but then I got a slight lag, reloaded the page and saw Exe6 was actually played.

**Comment by gbtami** [comment]
I can imagine that your connection was cut off for a short time (while you played Bxe6) and after re-connection your Exe6 pre-move was sent as next move.
Seems client side code doesn't handle this scenario in correct way. It should re-send your normal move Bxe6 instead of Exe6 in this case.
Thx for reporting this!
