### ISSUE TITLE
Capablanca960 should skip initial positions with unprotected pawns

### ISSUE THREAD

**Issue by agt-the-walker** [gbtami/pychess-variants#336]
This is not currently the case:
- https://github.com/gbtami/pychess-variants/blob/b2ccea51410702d9d902e32c3252d4a6ec1d80ce/server/fairy.py#L125
- https://www.pychess.org/HzM4M13g (where h pawn is unprotected)

Let's have a look at the following X-FEN:
bnrbqakcnr/pppppppppp/10/10/10/10/PPPPPPPPPP/BNRBQAKCNR w KQkq - 0 1

It respects all the rules in https://en.wikipedia.org/wiki/Capablanca_random_chess#Rules except "All pawns must be protected in the initial setup". Indeed both a and i are unprotected.

Unfortunately white can play 1.Ae3, which threatens both Axi7# and Axa7 (followed by Axc8 since the rook is unprotected), and it's not possible to defend against both threats.

**Comment by gbtami** [comment]
Telling the truth I'm not a big fan of this somehow arbitrary sub-rule. While It is true that in all 960/random variants there are several more or less unbalanced starting positions, the reason of imbalance in a given position is not necessarily because of existence of unprotected pawns.
![https://i.imgur.com/oQbs7Xk.png](https://i.imgur.com/oQbs7Xk.png)

**Comment by gbtami** [comment]
Not to mention that in other 960 variants no similar restriction exist at all. All in all I think implementing this sub-rule just for capa960 is not worth the effort and just breaks the 960 variants consistency in general. (We have chess960, zh960, capa960 and capazh960!)
