### ISSUE TITLE
Seirawan subvariant idea

### ISSUE THREAD

**Issue by Nordlandia** [gbtami/pychess-variants#34]
This is an suggestion based on Seirawan Chess. The board is 8x8 with four additional squares. 

Instead of the drop system used in Seirawan, the new pieces is already in the game at the start of the game.  I'm not sure but i think it's preferable to disable the extra squares once the fairy pieces has left their starting position.  The additional squares may be disabled for the rest of the games once the  fairy pieces has left their starting squares.   The giraffe chess board is somewhat odd but modification is good idea to rule out the drop system. 

![giraffe board](https://user-images.githubusercontent.com/26534454/66074387-66bca580-e559-11e9-9321-50d3a5c706a2.png)

**Comment by gbtami** [comment]
Pychess-variants  is heavily based on Fairy-Stockfis. I use it for move generation, validation, SAN conversion, analysis, BOT play, etc-etc. Because of this I can add variants only supported by Fairy-Stockfish. Until it is not there I have to close this issue, sry.

**Comment by Nordlandia** [comment]
What do you think about the suggestion in general? 

Do you like the suggestion?

**Comment by ianfab** [comment]
Variants with non-rectangular boards have been briefly discussed at https://github.com/ianfab/Fairy-Stockfish/issues/1 and in principle it should be feasible to integrate into Fairy-Stockfish, but the move generation would need quiet some adaption to support such board shapes, so it is unlikely to be supported in the near future.

Just now I had the idea for an easier workaround. As part of the Xiangqi implementation, I anyway will have to implement the possibility to restrict the mobility of pieces to a certain area, so one could just use a full 8x10 board and disallow any piece to move to the first and tenth rank. However, as mentioned, such feature requests rather belong to the Fairy-Stockfish repo, since the rules need to be implemented there first.

**Comment by Nordlandia** [comment]
Seems like a lot of work for a mere subvariant.

**Comment by CouchTomato87** [comment]
That's actually a pretty slick solution though, ianfab

**Comment by gbtami** [comment]
@Nordlandia I like the gating in S-chess because it creates more possibilities (opening/middle game variations) than this suggestion or Musketeer chess method.

**Comment by Nordlandia** [comment]
@gbtami i know few have mentioned that they find the drop or gating system confusing so this is an compromise.

**Comment by gbtami** [comment]
If someone find drop/gating confusing but want to try H/E he/she can choose Capa/Gothic/Grand :)

**Comment by Nordlandia** [comment]
Those board compromises general piece values and especially knight value. On 10x8, the knight devaluate and even more on 10x10.
