### ISSUE TITLE
Shogi SFEN

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#36]
This one would actually be a huge quality-of-life improvement for me. A lot of people use the ShogiGUI software for running engine analyses, and one of the only ways to get a game outside of downloading and loading a .kifu is by pasting notation in -- most likely going to be SFEN in this case.

So far, in order to analyze my games under the engine, I've had to replay the game myself on the engine, which is time-consuming to say the least. I know you pretty much have an analysis feature going at this moment (which is going to be VERY useful for quick analysis), but I still turn to the strongest available engine when I want deep analysis.

What would be helpful then is a link for "copy SFEN to clipboard" or something. Here are a few examples of SFENs generated by ShogiGUI:

1. A standard game with checkmate:

position startpos moves 2g2f 3c3d 7g7f 5c5d 4i5h 8b5b 2f2e 2b3c 8h3c+ 2a3c 2e2d 2c2d 2h2d 3d3e 2d2c+ 5b2b 2c3c 2b2i+ 5i6h B*4d 3c4c 4d9i+ N*5c 3a3b 5c4a+ 3b4a B*1e P*4b 4c5d 6a5b 8i7g L*5c 5d2d 2i3i 6i7h N*4e G*8i 5c5g+ 5h5g S*5i 6h6i 4e5g 6i5h 3i4h 5h4h win

2. A handicap game won by resignation:

position sfen 4k4/9/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL w - 1 moves 5a4b 2g2f 4b3b 7g7f 3b2b 2f2e 2b3b 2e2d 2c2d 2h2d P*2c 2d2e 3b2b 2e7e 2b3b 7e7c+ 2c2d 7c6c 3b2c 6c5c 2c3d 5c5e 1c1d 8h6f 9c9d 6f9c+ 2d2e 3g3f 2e2f 4i3h 4c4d 3h3g 4d4e 9c8c 2f2g+ 3g2g 9d9e 8c6a 3d2c 5e4e 2c3b 6a5b 3b2c 4e4d 2c3b 4d4c 3b2b 5b4a 2b1c 4c3c 1c1b 3c2c 1b1a 4a3a 1d1e 2c2b resign

3. A handicap game won by timeout:

position sfen 3gkg3/9/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL w - 1 moves 4a3b 7g7f 6a7b 6g6f 5a6b 6i7h 7c7d 7i6h 7b7c 6h7g 7c8d 9g9f 7d7e 8h9g 7e7f 7g7f 9c9d 7h7g 4c4d 8g8f 3b4c 2g2f 3c3d 2f2e 4c3c 2h2f 3c3b 2e2d 2c2d 2f2d 6b5b 2d2a+ 5b4c 2a2e 9d9e 8f8e 9e9f 9g8f 8d7d 6f6e 8c8d 6e6d 6c6d 9i9f P*9h

**Comment by ianfab** [comment]
Currently Fairy-Stockfish can not generate SFEN but only parse it, since it internally always uses FEN, , that is why pychess-variants only displays FEN for shogi.

However, the examples you mentioned are not [SFEN](https://en.wikipedia.org/wiki/Shogi_notation#SFEN), but USI position commands (which might or might not include an SFEN). It seems strange to me that the GUI exposes that to the user instead of using pure SFEN notation.

**Comment by CouchTomato87** [comment]
So the FEN/SFEN part is only really used for the starting position. If only standard games were done, I guess it's USI (plus drop commands iin standard notation style). Would that be feasible?

**Comment by ianfab** [comment]
It would be feasible, but to me it does not make sense unless this is really used consistently among GUIs, but I would assume that most GUIs use SFEN and not something that is only supposed to be used for engine communication. Implementing SFEN instead of FEN for shogi however of course makes sense to me.

**Comment by ianfab** [comment]
@gbtami I implemented the generation of SFEN, but currently it does not have any effect expect for outputting the SFEN in return to the "d" command. However, after merging it to the python wrapper, it is easy to report the FEN or SFEN depending on the variant in pyffish_getFEN.

**Comment by gbtami** [comment]
Cool, thx a lot!

**Comment by CouchTomato87** [comment]
What I'm requesting is output like one of the ones I posted above... I think most of it is USI (which I think is the "4b3b" kind of thing?), but drops are like R*3b, and starting position is SFEN.

The syntax appears to be like position X moves X, where X is either "startpos" for a standard game, or an SFEN as above for handicap games. moves X where X is the USI-ish movelist, ending in "win", "resign", or I guess nothing in the case of timeout.

**Comment by ianfab** [comment]
Sorry, I misread the initial post. I thought that ShogiGUI uses it for position representation, but now I understand it is for game representation.

A few clarifications:
- [SFEN](https://en.wikipedia.org/wiki/Shogi_notation#SFEN) is an exchange format for shogi positions, designed for several purposes, e.g., copying positions from one GUI to another, or for communication between GUI and engine. Example: `4k4/9/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL w - 1`
- *Coordinate notation* is a move notation mainly used by protocols such as USI. Examples: `7g7f`, `P*7f`
- [USI](http://hgm.nubati.net/usi.html) is a communication protocol between GUIs and engines
- The `position` command of the USI protocol is used by GUIs to inform the engine about the current position. It uses SFEN to describe the starting position (or alternatively "startpos") and the moves starting from that position in coordinate notation. Example: `position sfen 4k4/9/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL w - 1 moves 5a4b 2g2f`

I.e., the GUI is using a position definition format from an engine communication protocol for game representation. This is a bit strange to me and I am curious whether there is any other GUI also using that. Since there already are plenty of game file formats for shogi (KIF, CSA, PSN), this further contributes to the mess of formats. I really have no idea which of the formats currently is the most used and which should be supported.

However, using SFEN instead of FEN as a position exchange format definitely makes sense to me, since to my knowledge at least that is pretty much standard among GUIs.

**Comment by gbtami** [comment]
@CouchTomato87 so you want something like this?
![shogi](https://user-images.githubusercontent.com/479964/66245433-fefb8b80-e70d-11e9-8eb2-f8280bd055c8.png)

**Comment by CouchTomato87** [comment]
That would EXACTLY be it! :D If you wanted to save space, you could even make that link that just copies that into your clipboard.

**Comment by CouchTomato87** [comment]
Thanks, but I'm not seeing any change. I still get the usual thing below the board:

[Event "PyChess casual game"]
[Site "https://pychess-variants.herokuapp.com/rJz8etZ9"]
[Date "2019.10.05"]
[Round "-"]
[White "CouchTomato87"]
[Black "Random-Mover"]
[Result "1-0"]
[TimeControl "60+0"]
[Variant "Shogi"]
[FEN "lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL[-] b - 1"]
[SetUp "1"]

1. R-4h P-8d 2. G-3h P-8e 3. S-6h P-8f 4. B-7i Px8g+ 5. R-4i +Px7g 6. K-5h Rx8i+ 7. P-1f +Rx7i 8. R-5i +Px6h 9. K-4i +Px6i 10. S-2h +Px5i 11. K-3i +P-4i 1-0

**Comment by CouchTomato87** [comment]
Nevermind, it was because you hadn't restarted yet!!
