### ISSUE TITLE
Discovery - You can gate any two pieces in S-Chess. 

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#380]
Discovered I can gate any two pieces using FEN strings in S-Chess. Here's the proof. 

bhkqebnr/pppppppp/8/8/8/8/PPPPPPPP/QHENKBBR[RNrn] w ABCDEFGHabcdefgh 0 1

It works. Thanks Gbtami. And don't worry you don't have to fix this one. The only thing I can't do is use 960 castling rules because you closed out that request. Are you going to fix the gating flaw where Pychess only looks at any two blank squares when there could be more than two?

**Comment by gbtami** [comment]
S-chess960 implementation is ready on pychess. I just disabled it because https://github.com/ianfab/stockfish.wasm is waiting for merge latest upstream Fairy fixes https://github.com/ianfab/stockfish.wasm/issues/5. Maybe I should just disable local analysis similar to Shogun/Orda/Synochess/Grandhouse (variants defined in variants.ini has issues still https://github.com/ianfab/stockfish.wasm/issues/4)

I can't really understand your latest question. Can you elaborate it more please?

**Comment by Curious2021** [comment]
In other words any piece other than the Hawk or the Elephant can be gated but will NOT appear in the gated section when you play. But they appear only when you vacate the back rank during a game. For example if I play Ng3 on the first move with White I'm given the chance to gate an extra queen because in the FEN string I requested Pychess to recognize the Queen to be a valid piece to gate on my turn because the FEN string explicitly requests the Queen be given this honor. Even though the FEN string is recognized and allows this configuration the Queen in this case is not listed as a gated piece to use.  It appears invisible as an option. Only when you vacate the back rank does the queen appear when you can click on it to replace an empty square.

**Comment by gbtami** [comment]
Visible pocket roles are defined by variant rules, so this is Hawk and Elephant for S-chess of course. Adding all available pieces seems a bad idea because it may cause lots of confusion. It is just a side effect of pychess/fairy implementation of S-chess that you can play this FEN in S-chess while it is clearly not S-chess :)

Gating is a special move type. By definition you can "gate" a new piece to the square where a first time moving piece moved from. Castling involves Rook and King, so you have two option where to gate. But never more.
