### ISSUE TITLE
Websocket reconnect doesn't refresh the game

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#468]
![https://cdn.discordapp.com/attachments/801765362873270313/820750311474856026/Untitled.png](https://cdn.discordapp.com/attachments/801765362873270313/820750311474856026/Untitled.png)
https://www.pychess.org/q03J0baR
"it happened on 5th move, i took bxd4 but after waiting 1 min, i had to refresh the page, then i saw my time has passed instead of his, also i lost the console logs after refreshing but before that i took this screenshot"

This may lead losing the game by time, because users never notice what happened.

**Comment by visualdenniss** [comment]
Also seemingly not only in game, but this applies to seeks in Lobby (seeks get lost even without changing tabs) : 
<img width="1005" alt="Screenshot 2021-03-15 at 22 46 07" src="https://user-images.githubusercontent.com/80699817/111212783-174d2680-85e1-11eb-8882-7a8525082e75.png"> This happened on a PC, Google Chrome.

this issue was addressed also in [https://github.com/gbtami/pychess-variants/issues/460#issue-820361558](url) as "Seek disappears when browser tab changes" for IpadPro-Safari, but it seems it is not only limited to Safari or Touch devices, as this case shows.

**Comment by gbtami** [comment]
Possible fix committed. Feel free to reopen if it happens again.

**Comment by visualdenniss** [comment]
![websocket](https://user-images.githubusercontent.com/80699817/116299852-dc750b80-a7a6-11eb-8698-fdd92819fd71.png)
I did not receive opponents move without refreshing manually.

**Comment by gbtami** [comment]
Isn't it possible that your opp just abandoned the game? Any move happened at all?

**Comment by nnickoloff1234** [comment]
This or similar bug can somewhat easily reproduce this locally if you:
1. Run 
`sudo tcpkill -i any -1 port 8080`
in console while playing a game (especially if your turn)

2. Wait a couple of seconds after running that command (you can also try -9 instead of -1) and then make a move.

3. You will see opponent's clock starts ticking and seemingly your move has been accepted.
4. Ctrl-C in the terminal where the tcpkill command is runnig, so it will stop killing all reconnects and pychess will successfully reconnect
5. At this moment YOUR clock will start ticking. However you are unable to move any piece (it marks them as pre-moves) and your last move still stays as played (but only on the board and never apparently reached the server)
6. Hit F5 to refresh the board - you will see your move was never accepted

---------------------------
//slightly offtopic:
Not sure if important but in my dev environment i also have this change to game.py to delay Random Movers moves so putting it here (i think it is worth coming up with permanent solution in dev mode to simulate such delays as it was first of all useful for me when working on premoves):

In gamy.py and i have added 
`           
        cur_time = monotonic()
        # BOT players doesn't send times used for moves
        if self.bot_game:


            if cur_player.bot:
                time.sleep(5)
                
            movetime = int(round((cur_time - self.last_server_clock) * 1000))
            # print(self.board.ply, move, movetime)
`
-------------------------

IMHO a message like in lichess that shows when connection is lost and regained would be at least helpful even if the original bug is harder to fix - i see those events are not hard to detect because in console there is log on those events already and user will at least know they will have to hit f5 and not get mislead it is opp's turn.

But ideally on reconnect my guess is some hard/full sync with server's state might be a good idea - not sure

**Comment by nnickoloff1234** [comment]
or even better way to reproduce instead of tcpkill this can be used:
```
#to disconnect:
sudo iptables -A INPUT -p tcp --destination-port 8080 -j DROP
#to reconnect
sudo iptables -D INPUT 1
```
