### ISSUE TITLE
Analysis board in dobutsu suggest the same moves

### ISSUE THREAD

**Issue by MistakeCorrect** [gbtami/pychess-variants#472]
Hello. Im in the Dobutsu shogi analysis, and i followed all the moves that Fairy Stockfish suggests.
PGN:
`1.Gc2 Ga3 2.Lc1 Ga2 3.Lb1 Gxa1+ 4.Lxa1 E@a3 5.G@a2 Cxb2 6.Gxa3 Lxa3 7.Gxb2 Eb3 8.C@a2+ Lb4 9.Lb1 G@c3 10.La1 Gc2 11.Gxc2 Exc2 12.E@a3+ Lc3 13.Eb2+ Lb4 14.G@c1 Eb3 15.Lb1 C@c3 16.Ea3+ Lc4 17.Eb2 Lb4 18.Ea3+ Lc4 19.Eb2 Lb4 20.Ea3+ Lc4 21.Eb2 Lb4 22.Ea3+ Lc4 23.Eb2 Lb4 24.Ea3+ Lc4`
See from move 18, if you try the analysis with the PGN, fairy stockfish will follow suggestin Ea3+ and Lc4.

**Comment by gbtami** [comment]
I can't see any problem here, but if you think Fairy-Stockfish is wrong, you can file an issue in https://github.com/ianfab/Fairy-Stockfish/issues

**Comment by visualdenniss** [comment]
i think Ea3+ and Lc4 suggestions have to do with that Fairy sees giving repetitive checks as loss for the side that is giving checks. So it comes up with that repetitive check suggestion here and then when you follow a certain line where it evals with lets say mate in 7 or so. 

It simply means, there are other ways for win as well, one is longer and is shorter.  And in case of multiple ways of win, fairy sometimes chooses this way of win (making the losing side lose by giving checks) over a real win with checkmate in a maybe longer/shorter line, since it sees both as ways of winning/losing. 

This is already issued in [https://github.com/ianfab/Fairy-Stockfish/issues/191](url) under "Three-fold repetition, including perpetual check, is a draw."
