### ISSUE TITLE
Strange bug in Dobutsu arena

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#647]
![https://i.imgur.com/gnLlPXi.png](https://i.imgur.com/gnLlPXi.png)

**Comment by gbtami** [comment]
This is a complete mystery form me. As I see "abandone" game end can happen only in on case, on users log out.
Maybe I accidentally poked around in the settings and clicked on log out button? But I can't remember I did it, nor I had to log in again at all. @nnickoloff1234 any idea?

**Comment by nnickoloff1234** [comment]
@gbtami 

Don't know really, but I took a look at relevant code trying hoping some ideas might spring out. 

I also do not see other way for an "abandone" status to be created except on logout.

Here https://github.com/gbtami/pychess-variants/blob/9bad418720275dc68804fe3b6f9c93ee903861c3/server/login.py#L168 
it means that if you have multiple HTTP sessions (different devices/browsers/etc.) if you open GET /logout in any of those sessions would result in abandoning all ongoing games in all other sessions. Something like this might explain part of the mystery - the part where you don't have recollection of logging out/in while we were playing.

So my best guess something like this happened, given that you haven't actually logged out from the session in which we were playing while we were playing, maybe you had an open pychess (or lichess) on another machine that someone else logged out from? Or you get-requested "/logout" url on some other browser without noticing? Or someone else managed to login with your username in another session somehow and logged out from it (which hopefully is not the case though, because sounds like a major security hole :) )?

**Comment by nnickoloff1234** [comment]
I mean i see a minor bug here, that, ideally, games should be associated to http sessions in addition or instead of (directly) to users so one logging out doesn't affect all user sessions like this, but the rest of what happened is still a mystery to me as well

**Comment by gbtami** [comment]
OK, I close this now as "black magic". If it happens again for anyone, we will reopen it.
