### ISSUE TITLE
Decide what to do about not getting extra point for berserking for winning in fewer than 7 moves

### ISSUE THREAD

**Issue by kezsulap** [gbtami/pychess-variants#862]
Example of how ridiculous it can get in atomic960: https://www.pychess.org/xN8RqiJl

**Comment by gbtami** [comment]
ubdip
 — 
Today at 12:14 PM
I do not really see a problem with that. It surely is a bit artificial or at least arbitrary, but with such quick wins you already have a double benefit (winning and saving time) and the berserking did not really have any effect on the game, so it is fine to not further exaggerate the advantage of quick wins, especially if it happened due to lucky pairings.

gbtami
 — 
Today at 12:16 PM
yep, I can agree with this myself
OK, I think we can let it as it is now
