### ISSUE TITLE
Bug in arena

### ISSUE THREAD

**Issue by NelloHo** [gbtami/pychess-variants#962]
the opponent 's movement won't be shown when the focus is not on the windows.
which means if I switch to another windows (i.e, youtube), the opponent 's next movement won't be moved unless I refresh the window again.

**Comment by MaxLand13** [comment]
Yeah, I lost a lot of ranking because of that issue in this [game](https://www.pychess.org/nqUvWkzc)
The tournament started, but I kept watching YouTube in another tab. When I noticed that the page refreshed and the game began, I switched to the pychess tab, my opponent did not make a move, I even made a premove, but after time expired, I lost.

**Comment by gbtami** [comment]
Provide more info, please.
Device, OS, browser?

**Comment by NelloHo** [comment]
device : ASUS laptop
OS: Linux & Windows all having the same problem
browser: chrome

**Comment by gbtami** [comment]
Should be fixed via https://github.com/gbtami/pychess-variants/commit/5267866ecb76d9f3932cb3f825d7c5300f81a6ff
Feel free to reopen if it happens again.
